# Copyright 2019 The original author or authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: kafka-provider
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: kafka-provider
      labels:
        app: kafka-provider
    spec:
      containers:
      - name: main
        image: github.com/projectriff/kafka-provider/cmd/provider
        env:
        - name: GATEWAY
          value: liiklus.default.svc.cluster.local:6565
        - name: BROKER
          value: kafkabroker:9092

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-provider
    projectriff.io/release: devel
  name: kafka-provider
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kafka-provider

